spring.application.name=langchain4j_springboot
langchain4j.community.dashscope.chat-model.api-key=${ALIAI_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-plus

langchain4j.community.dashscope.streaming-chat-model.api-key=${ALIAI_API_KEY}
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-plus

langchain4j.community.dashscope.embedding-model.api-key=${ALIAI_API_KEY}
#langchain4j.community.dashscope.embedding-model.model-name=qwen-max

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.timeout=60s
spring.ai.openai.chat.options.connect-timeout=60s
spring.ai.openai.chat.options.read-timeout=60s

spring.ai.ollama.server-url=http://localhost:11434
spring.ai.ollama.chat.options.model=deepseek-r1:1.5b

#spring.ai.qianfan.api-key=
#spring.ai.qianfan.secret-key=

# GitHub????
# ???????GitHub????URL
github.document.url=https://raw.githubusercontent.com/iZfx/KnowledgeBase/main/SportHeatMap.txt

# 定时任务配置
# 是否跳过定时任务执行（true-跳过，false-正常执行）
scheduler.document.update.skip=true

logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.springframework.web=DEBUG

# ??????
server.port=8080
server.error.include-message=always

# Tomcat????
server.tomcat.max-connections=8192
server.tomcat.accept-count=100
server.tomcat.max-threads=200
server.tomcat.relaxed-query-chars=|,{,},[,]
server.tomcat.reject-illegal-header=false

# ???????HTTPS???
# ?????HTTPS????????HTTP???
# ???????????
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.remote-ip-header=x-forwarded-for
server.forward-headers-strategy=native

# ?????
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info
